#!/bin/bash -e -v -x

baseDir=${WORKSPACE-`pwd`}
scriptsDir="$baseDir/scripts"
. $scriptsDir/common

function runsbt() {
  $SBT_CMD \
     -Dstarr.version=$scalaVersion \
     "setupValidateTest $prRepoUrl" \
     $testExtraArgs \
     "$@"
}

case $prDryRun in

  yep)
    echo "DRY RUN"
    ;;

  *)

    # Download the auxiliary JARs in test/files/lib:
    # TODO We should find a better way to fetch them once ant is gone
    ./pull-binary-libs.sh

    # build quick using STARR built upstream, as specified by scalaVersion
    # (in that sense it's locker, since it was built with starr by that upstream job);
    # and run JUnit tests
    runsbt "test"

    # multiple invocations to conserve PermGen
    runsbt "partest run pos"
    runsbt "partest neg jvm"
    runsbt "partest res scalap"
    runsbt "partest specialized scalacheck"
    runsbt "partest instrumented presentation"

    runsbt "partest --srcpath scaladoc"

    # Migration Manager; make sure Scaladoc doesn't bomb
    runsbt mima doc

    ;;

esac
